<?php

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.
// Returns the private 'argument_resolver.service' shared service.

include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentValueResolverInterface.php';
include_once $this->targetDirs[3].'/vendor/symfony/http-kernel/Controller/ArgumentResolver/ServiceValueResolver.php';

return $this->services['argument_resolver.service'] = new \Symfony\Component\HttpKernel\Controller\ArgumentResolver\ServiceValueResolver(new \Symfony\Component\DependencyInjection\ServiceLocator(array('App\\Controller\\DefaultController:login' => function () {
    return ${($_ = isset($this->services['service_locator.yi1lo74']) ? $this->services['service_locator.yi1lo74'] : $this->load('getServiceLocator_Yi1lo74Service.php')) && false ?: '_'};
}, 'App\\Controller\\DefaultController::login' => function () {
    return ${($_ = isset($this->services['service_locator.yi1lo74']) ? $this->services['service_locator.yi1lo74'] : $this->load('getServiceLocator_Yi1lo74Service.php')) && false ?: '_'};
})));
