<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerMhxjei0\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerMhxjei0/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerMhxjei0.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerMhxjei0\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerMhxjei0\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Mhxjei0',
    'container.build_id' => 'e06eecc6',
    'container.build_time' => 1524072862,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerMhxjei0');
