<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVke61rs\srcDevDebugProjectContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVke61rs/srcDevDebugProjectContainer.php') {
    touch(__DIR__.'/ContainerVke61rs.legacy');

    return;
}

if (!\class_exists(srcDevDebugProjectContainer::class, false)) {
    \class_alias(\ContainerVke61rs\srcDevDebugProjectContainer::class, srcDevDebugProjectContainer::class, false);
}

return new \ContainerVke61rs\srcDevDebugProjectContainer(array(
    'container.build_hash' => 'Vke61rs',
    'container.build_id' => 'a1892ee5',
    'container.build_time' => 1524021801,
), __DIR__.\DIRECTORY_SEPARATOR.'ContainerVke61rs');
